apiVersion: agent-install.openshift.io/v1beta1
kind: SiteConfig
metadata:
  name: "opp-prod-standalone"
  namespace: "opp-nprod"
spec:
  pullSecretRef:
    name: "assisted-installer-pull-secret"
  clusterImageSetNameRef: "img4.20.0-x86-64-appsub" 
  clusters:
    - clusterName: "standalone-cluster"
      networkType: "OVNKubernetes"
      clusterLabels:
        cloud: "OpenShiftVirt"
        vendor: "OpenShift"
      nodes:
        # --- NÓ MASTER 0 ---
        - hostName: "master-0.standalone.com"
          role: "master"
          bmcAddress: "virt-it+https://api.malima.rhbr-lab.com:6443" 
          bmcCredentialsName:
            name: "bmc-secret-standalone"
          bootMACAddress: "02:00:00:00:00:01" 
          nodeNetwork:
            interfaces:
              - name: eth0
                macAddress: "02:00:00:00:00:01"
            config:
              interfaces:
                - name: eth0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.36.41.82
                        prefix-length: 16
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 10.36.64.243
                    next-hop-interface: eth0
              dns-resolver:
                config:
                  server:
                    - 10.36.41.51 

        # --- NÓ MASTER 1 ---
        - hostName: "master-1.standalone.com"
          role: "master"
          bmcAddress: "virt-it+https://api.malima.rhbr-lab.com:6443" 
          bmcCredentialsName:
            name: "bmc-secret-standalone"
          bootMACAddress: "02:00:00:00:00:02" 
          nodeNetwork:
            interfaces:
              - name: eth0
                macAddress: "02:00:00:00:00:02"
            config:
              interfaces:
                - name: eth0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.36.41.83
                        prefix-length: 16 
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 10.36.64.243
                    next-hop-interface: eth0
              dns-resolver:
                config:
                  server:
                    - 10.36.41.51                       

        # --- NÓ MASTER 2 ---
        - hostName: "master-2.standalone.com"
          role: "master"
          bmcAddress: "virt-it+https://api.malima.rhbr-lab.com:6443" 
          bmcCredentialsName:
            name: "bmc-secret-standalone"
          bootMACAddress: "02:00:00:00:00:03" 
          nodeNetwork:
            interfaces:
              - name: eth0
                macAddress: "02:00:00:00:00:03"
            config:
              interfaces:
                - name: eth0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.36.41.84
                        prefix-length: 16
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 10.36.64.243
                    next-hop-interface: eth0
              dns-resolver:
                config:
                  server:
                    - 10.36.41.51                                  
     
      installConfigOverrides: |
        {
          "controlPlane": { "replicas": 3 },
          "compute": [ { "replicas": 0 } ]
        }